<?php 
	$this->headTitle('Accueil');
	$this->headMeta()->appendName('Description', "Bienvenue sur la page d'accueil");
?>

<!-- Affichage des articles -->
<h1>Nos récents articles</h1>
<?php 
foreach ($this->articles as $indiceArticle => $article )
{
?>
	<div style="width: 800px; display:inline-block; vertical-align:top;">
		<h2 style="font-size:22px"><?php echo $article['articles_titre']; ?></h2>
		<p><?php echo $article['articles_contenu']; ?></p>
	</div>
	<div style="width: 200px; display:inline-block; vertical-align:top; margin: 0 0 0 10px">
		<h3 style="margin: 60px 0 10px 0; font-size: 20px">Informations complémentaires</h3>
		<p><span style="font-weight: bold; font-size:11px;">Auteur : </span><?php 
			foreach($this->auteurs as $indiceAuteur => $auteur)
			{
				if($auteur['auteurs_id'] == $article['articles_auteur'])
				{
					echo $auteur['auteurs_nom'] . ' ' . $auteur['auteurs_prenom'] ; ?></p>
			<?php
				}
			}
			?>
		<p><span style="font-weight: bold; font-size:11px;">Date :</span> <?php echo $article['articles_date']; ?></p>
	</div>
<?php 
}
?>

<!-- Lien pour aller sur la page Contact -->
<div id="contact" style="text-align: center;">
	<a href="<?php echo $this->url(array(), 'contactIndex');?>" style="color:black; font-style:italic; font-weight:bold;">Nous contacter</a><br/>
</div>
